project:
  type: website
  output-dir: docs

website:
  title: "Anita Simha"
#  logo: logo.png
  navbar:
    left:
      - research.qmd
      - teaching.qmd
      - publications.qmd
    search: true
  bread-crumbs: false
  page-footer: 
    background: light
    left: 
      - icon: "{{< iconify academicons:google-scholar >}}"
        href: "https://scholar.google.com/citations?user=4y2-7_kAAAAJ&hl=en"

  

format:
  html:
    theme:
      - lux
      - theme.scss
    css: styles.css
    toc: true

editor: source

